### ISSUE TITLE
The referenced filter product is named "Brita" instead of "Britta"

### ISSUE THREAD

**Issue by brittag** [antifuchs/gmail-britta#12]
This is just for fun - my name is Britta, and I randomly found this repository while googling something unrelated. As a Britta, I can tell you that the water filter brand spells its name with only one t: https://www.brita.com/ :)

**Comment by antifuchs** [comment]
Haha, yep - the naming here was as much a play on the Community character as a typo'd reference to the water filters! (I guess I could try to retcon my dignity back by saying it's a fully intentional pun, but it really isn't; and my dignity is definitely impaired by my usual punning anyway!)

Thanks for the note, at any rate! I hope gmail-britta can be useful to you some day, should you need it! (:
